baseURL: https://modelbased.cloud
title: Model Based Innovation LLC
theme: ma-hugo-theme
params:
  logo: /images/LogoWhiteFont.svg
  darkMode: false
  email: info@modelbased.cloud
  linkedin: hubertus-tummescheit-5220752
ignorelogs: warning-goldmark-raw-html
menus:
  main:
    - pageRef: "company"
      identifier: "company"
      name: "Company"
      url: "/company/"
      weight: 5
      
    - pageRef: "libraries"
      identifier: "libraries"
      name: "Libraries"
      url: "/libraries/"
      weight: 2      
      
    - pageRef: "tools"
      identifier: "tools"
      name: "Tools"
      url: "/tools/"
      weight: 1
 
    - pageRef: "FMI"
      identifier: "FMI"
      name: "FMI"
      url: "/tools/fmi/"
      parent: "tools"
      weight: 2

    - pageRef: "SSP"
      identifier: "SSP"
      name: "SSP"
      url: "/tools/ssp/"
      parent: "tools"
      weight: 3

    - pageRef: "Modelica"
      identifier: "Modelica"
      name: "Modelica"
      url: "/tools/modelica/"
      parent: "tools"
      weight: 1      
          
    - pageRef: "services"
      identifier: "services"
      name: "Services"
      url: "/services/"
      weight: 1


